spring:
  # 排除掉druid原生的自动配置
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      druid: # 以下是全局默认值，可以全局更改
        # 监控统计拦截的filters
        filters: stat
        # 配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        # 获取连接等待超时时间
        max-wait: 60000
        # 间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        # 一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      primary: db1 # 设置默认的数据源或者数据源组,默认值即为db1
      strict: false # 设置严格模式,默认false不启动,启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源
      datasource:
        db1:
          url: jdbc:mysql://127.0.0.1:3306/db01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        db2:
          url: jdbc:mysql://127.0.0.1:3306/db02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size:
            validation-query: select 1 FROM DUAL # 比如oracle就需要重新设置这个
            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter。

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
